import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
async function createProblem(formData: FormData) {
  "use server";
  const { supabase, userId } = await requireAdmin();
  const title=String(formData.get("title")??"").trim(), slug=String(formData.get("slug")??"").trim().toLowerCase(), statement=String(formData.get("statement")??"").trim();
  if(!title||!slug||!statement) throw new Error("Title, slug and statement are required.");
  const {data,error}=await supabase.from("problems").insert({title,slug,statement,difficulty:String(formData.get("difficulty")??"medium"),time_limit_ms:Number(formData.get("time_limit_ms")??2000),memory_limit_mb:Number(formData.get("memory_limit_mb")??256),input_format:String(formData.get("input_format")??""),output_format:String(formData.get("output_format")??""),constraints:String(formData.get("constraints")??""),explanation:String(formData.get("explanation")??""),created_by:userId}).select("id").single();
  if(error) throw new Error(error.message); redirect(`/admin/problems/${data.id}`);
}
export default function NewProblemPage(){return <main className="container"><div className="card form-card"><p className="eyebrow">Admin • Problems</p><h1>Create problem</h1><form action={createProblem} className="form-grid"><label>Title<input name="title" placeholder="The Festival Lights" required/></label><label>Slug<input name="slug" placeholder="festival-lights" required/></label><label>Difficulty<select name="difficulty"><option>easy</option><option value="medium">medium</option><option>hard</option></select></label><label>Time limit (ms)<input name="time_limit_ms" type="number" min="100" defaultValue="2000"/></label><label>Memory (MB)<input name="memory_limit_mb" type="number" min="16" defaultValue="256"/></label><label className="full">Statement<textarea name="statement" rows={8} required placeholder="Write the complete problem statement..."/></label><label className="full">Input format<textarea name="input_format" rows={3}/></label><label className="full">Output format<textarea name="output_format" rows={3}/></label><label className="full">Constraints<textarea name="constraints" rows={3}/></label><label className="full">Explanation<textarea name="explanation" rows={3}/></label><div className="full"><button className="btn" type="submit">Create problem</button></div></form></div></main>}
